# Generated by Django 4.1 on 2024-03-05 10:15

from django.db import migrations, models
import toppage.models


class Migration(migrations.Migration):
    dependencies = [
        ("toppage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ourposts",
            name="photo1",
            field=models.ImageField(
                blank=True,
                upload_to="images/",
                verbose_name="写真",
            ),
        ),
    ]
